@url = http://localhost:8080/api

### -----------------------------
### LOGIN USUARIO 1
### -----------------------------
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "diablojuega1@gmail.com",
  "password": "1234"
}

### -----------------------------
### LOGIN USUARIO 2
### -----------------------------
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "diablojuega@gmail.com",
  "password": "1234"
}

### -----------------------------
### PRODUCTOS (PÚBLICO)
### -----------------------------
GET {{url}}/products
Accept: application/json

GET {{url}}/products/show/1
Accept: application/json

### -----------------------------
### FAVORITOS - USUARIO 1
### -----------------------------
### Listar
GET {{url}}/favorites
Authorization: Bearer 3|lUpZD7AsbH99zw7msZihUQq7MED9nHuBLI5Z7XrR60739cdd
Accept: application/json

### Crear favorito (id_product=1)
POST {{url}}/favorites/store
Authorization: Bearer 3|lUpZD7AsbH99zw7msZihUQq7MED9nHuBLI5Z7XrR60739cdd
Content-Type: application/json
Accept: application/json

{
  "id_product": 1
}

### Volver a listar para ver id_favorite creado
GET {{url}}/favorites
Authorization: Bearer 3|lUpZD7AsbH99zw7msZihUQq7MED9nHuBLI5Z7XrR60739cdd
Accept: application/json

### Eliminar favorito (ajusta el ID si no es 1)
DELETE {{url}}/favorites/destroy/1
Authorization: Bearer 3|lUpZD7AsbH99zw7msZihUQq7MED9nHuBLI5Z7XrR60739cdd
Accept: application/json

### -----------------------------
### FAVORITOS - USUARIO 2
### -----------------------------
### Listar
GET {{url}}/favorites
Authorization: Bearer 4|B8EdENxXMt22p1VYDAwDtnfe0UEfnpleLIWjdlIc8dea56e9
Accept: application/json

### Crear favorito (id_product=1)
POST {{url}}/favorites/store
Authorization: Bearer 4|B8EdENxXMt22p1VYDAwDtnfe0UEfnpleLIWjdlIc8dea56e9
Content-Type: application/json
Accept: application/json

{
  "id_product": 1
}

### Volver a listar para ver id_favorite creado
GET {{url}}/favorites
Authorization: Bearer 4|B8EdENxXMt22p1VYDAwDtnfe0UEfnpleLIWjdlIc8dea56e9
Accept: application/json

### Eliminar favorito (ajusta el ID si no es 1)
DELETE {{url}}/favorites/destroy/1
Authorization: Bearer 4|B8EdENxXMt22p1VYDAwDtnfe0UEfnpleLIWjdlIc8dea56e9
Accept: application/json

